name: 'self hosted runner demo'

on: workflow_dispatch

jobs:
  hello-self-hosted-runner:
    runs-on: self-hosted
    steps: 
    - name: run-me-inside-self-hosted-runner
      run:  echo "Howdy GitHub Actions. I know I am getting executed inside self hosted runner."

    - name: sleep for 60 seconds
      run: sleep 60
