# Ceci est mon est
#
name: TestStef
on:
  push:
    branches:
      - "main"

  workflow_dispatch:
env:
  Prenom: Marc
  Nom: Bernardin


jobs:
  monjob1:
    runs-on: ubuntu-latest
    steps:
      - name: step11
        id: step11_ID
        run: |
          echo "Bonjour ${{env.Prenom}}, ton nom est ${{env.Nom}}"
          echo "age=18" >> $GITHUB_ENV
    
      - name: step12
        id: step12_ID
        run: |
          echo "son age ${{env.age}}"
          echo "mot de passe ${{secrets.MONPASSWORD}}"
      
      - name: step13
         run "contenu de mon artefact" > artefact.txt
        uses: actions/upload-artifact@v4
          with:
            name: file
            path: artefact.txt
            retention-days: 10

  monjob2:
    name: "Le job2"
    runs-on: ubuntu-latest
    need: monjob1
    env:
      Prenom: Jacques

    steps:
      - name: use action-download
        uses: actions/download-artifact@v4
          with:
            name: file
            path: artifact.txt

      - name: step21
        id: step21_ID
        run: |
          echo "Le Prenom global ${{env.Prenom}}"
          echo "Le Prenom local $Prenom"
          echo "Le nom ${{env.Nom}}"
          echo "L'age ${{env.age}}"
          ls -rtl

      - name: step22
        run: cat artefact.txt
  