# Ceci est mon est
#
name: TestStef
on:
  push:
    branches:
      - "main"

  workflow_dispatch:
env:
  Prenom: Marc
  Nom: Bernardin


jobs:
  monjob1:
    runs-on: ubuntu-latest
    steps:
      - name: step11
        id: step11_ID
        run: |
          echo "Bonjour ${{env.Prenom}}, ton nom est ${{env.Nom}}"
          echo "age=18" >> $GITHUB_ENV
    
      - name: step12
        id: step12_ID
        run: |
          echo "son age ${{env.age}}"
          echo "mot de passe ${{secrets.MONPASSWORD}}"
      
      - name: step13
        run: echo "contenu de mon artefact" > artefact.txt

      - name: step14
        uses: actions/upload-artifact@v4
        with:
          name: file
          path: artefact.txt
          retention-days: 10

  monjob2:
    name: "Le job2"
    runs-on: ubuntu-latest
    needs: monjob1

    env:
      Prenom: Jacques

    steps:
      - name: use action-download
        uses: actions/download-artifact@v4
        with:
          name: file

      - name: step21
        id: step21_ID
        run: |
          echo "Le Prenom global ${{env.Prenom}}"
          echo "Le Prenom local $Prenom"
          echo "Le nom ${{env.Nom}}"
          echo "L'age ${{env.age}}"
          ls -rtl

      - name: step22
        run: cat artefact.txt
  
  monjob3:
    name: "secret en prod"
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: "affiche le secret"
        run: |
          echo "APP_SECRET: ${{secrets.APP_SECRET}}"

  monjob4:
    name: "variables env dans workflow"
    runs-on: ubuntu-latest
    steps:
      - name: "cree var env"
        id: cree_var_env
        run: |
          echo "creation des variables"
          # echo "::set-output name=varenv1::LaVariable"
          # echo "::set-output name=varenv2::$(date +'%Y-%m-%d-%H-%M')"
          echo "varenv1=TechSckool" >> "$GITHUB_OUTPUT"
          echo "varenv2=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"

      - name: "affiche var env"
        run: |
          echo varenv1: ${{ steps.cree_var_env.outputs.varenv1 }} 
          echo varenv2: ${{ steps.cree_var_env.outputs.varenv2 }} 