# Ceci est mon est
#
name: TestStef
on:
  push:
    branches:
      - "main"

  workflow_dispatch:
env:
  Prenom: Marc
  Nom: Bernardin


jobs:
  monjob1:
    runs-on: ubuntu-latest
    steps:
      - name: step11
        run: echo "Bonjour ${{env.Prenom}}, ton nom est ${{env.Nom}}"

  monjob2:
    name: "Le job2"
    runs-on: ubuntu-latest

    env:
      Prenom: Jacques

    steps:
      - name: step12
        run: |
          echo "Bonjour ${{Prenom}}, ton nom est ${{Nom}}"
          ls -rtl
